### ISSUE TITLE
Hangs occured when C++ program calls the Iceoryx2 API

### ISSUE THREAD

**Issue by qpswwww** [eclipse-iceoryx/iceoryx2#251] opened 2024-06-21 15:24 UTC
I'm planning to use iceoryx2 as the low-latency IPC method for my project's C++ client and Rust server. Recently I've tried to wrap iceoryx2 into my C++ client using Rust-CXX. However, I observed that, when the C++ client uses std::thread to create threads and call iceoryx2 in the spawned thread, it sometimes hangs. This bug can be reproduced on both Mac OS (Mac M1) and Linux (x86 CPU).

To the best of my knowledge, iceoryx2 is the fastest IPC method for Rust programs. It seems that iceoryx2 is the only viable solution for my project. So I really hope this bug can be resolved ASAP. I'm eagerly looking forward to a solution and a matured (or premature) C++ library of iceoryx2. Thanks!

**Comment by elBoberido** [comment] 2024-06-21 15:37
@qpswwww do you have a minimal example? Ideally with build instructions. Are you using a released version or the main branch?

We are currently also working on official C and C++ bindings. They should be available at the end of June (C) and end of July (C++).

**Comment by qpswwww** [comment] 2024-06-22 01:20
> @qpswwww do you have a minimal example? Ideally with build instructions. Are you using a released version or the main branch?
> 
> We are currently also working on official C and C++ bindings. They should be available at the end of June (C) and end of July (C++).

For your information, I post my client code here. I have read the current C example in iceoryx2, but it is only single-threaded. I suggest considering the C++ multi-thread scenario. Because we usually call the APIs in a spawned thread.

This is the C++ part:

```cpp
#include <iostream>
#include "rust_part.h"
#include <thread>
#include <chrono>
#include "unistd.h"
#include "build/rust_part/rust_part.h"

void test_request_launch_kernel(int base_id) {
    for(int i=0;i<100;i++) {
        std::cout<<"C++ call launch " << base_id+i << std::endl;
        rust_part::send_request_to_server(base_id+i);
        std::cout<<"C++ finished call launch " << base_id+i << std::endl;
        usleep(10);
    }
}

int main()
{
    rust_part::launch_request_service_daemon();
    rust_part::launch_reply_service_daemon();
    std::thread th2(test_request_launch_kernel, 0);
    std::thread th3(test_request_launch_kernel, 10000);
    std::thread th4(test_request_launch_kernel, 10000000);
    th2.join();
    th3.join();
    th4.join();
    return 0;
}
```

Rust part client code:
```rust
#[cxx::bridge]
mod ffi {
    #[namespace = "rust_part"]
    extern "Rust" {
        fn send_request_to_server(client_id: u64);
        fn launch_request_service_daemon();
        fn launch_reply_service_daemon();
    }
}

fn launch_request_service_daemon() {
    let (_, request_channel_recver) = request_channel.clone();
    let request_service_name = match ServiceName::new("My/Funk/ServiceName") {
        Ok(val) => val,
        Err(err) => {
            println!("Failed to create service name, {}", err);
            exit(233)
        }
    };

   let request_service = match zero_copy::Service::new(&request_service_name)
        .publish_subscribe()
        .open_or_create::<MessageStruct>() {
        Ok(val) => {
            println!("Publish service Created.");
            val
        },
        Err(err) => {
            println!("Failed to create service, {}", err);
            exit(233)
        }
   };

    let request_publisher = match request_service.publisher().create() {
        Ok(val) => val,
        Err(err) => {
            println!("Failed to create request service publisher, {}", err);
            exit(233)
        }
    };
    loop {
        match request_channel_recver.recv() {
            Err(err) => {
                println!("Failed to loan uninit(), {}", err);
                return;
            }
            Ok(request_msg) => {
                match request_publisher.loan_uninit() {
                    Err(err) => {
                        println!("Failed to loan uninit(), {}", err);
                        return;
                    }
                    Ok(val) => {
                        let sample = val.write_payload(request_msg);
                        match sample.send() {
                            Ok(..) => {println!("Send a reply")}
                            Err(err) => println!("Failed to send reply, {}", err)
                        }
                    }
                };
            }
        }
    }
}

fn launch_reply_service_daemon() {
    let reply_service_name = match ServiceName::new("My/Funk/ReplyFromServer") {
        Ok(val) => val,
        Err(err) => {
            println!("Failed to create service name, {}", err);
            exit(233)
        }
    };

    let reply_service = match zero_copy::Service::new(&reply_service_name)
        .publish_subscribe()
        .open_or_create::<ReplyStruct>() {
        Ok(val) => {
            println!("Publish service Created.");
            val
        },
        Err(err) => {
            println!("Failed to create service, {}", err);
            exit(233)
        }
    };

    let reply_subscriber = match reply_service.subscriber().create() {
        Ok(val) => val,
        Err(err) => {
            println!("Failed to create reply service subscriber, {}", err);
            exit(233)
        }
    };
    while let Iox2Event::Tick = Iox2::wait(Duration::ZERO) {
        loop {
            let received_data = reply_subscriber.receive();
            match received_data {
                Ok(val) => {
                    match val {
                        Some(val) => {
                            println!("Received reply: {:?}", val);
                        }
                        _ => {}
                    }
                }
                Err(err) => println!("Failed to receive data, {}", err),
            }
        }
    }
}

fn send_request_to_server(client_id: u64) {
    let msg = MessageStruct{
        client_id: client_id,
    };
    let (request_channel_sender, request_channel_recver) = request_channel.clone();
    request_channel_sender.send(msg).expect("Failed to send request to the request channel")
}
```

**Comment by qpswwww** [comment] 2024-06-22 10:17
> @qpswwww do you have a minimal example? Ideally with build instructions. Are you using a released version or the main branch?
> 
> We are currently also working on official C and C++ bindings. They should be available at the end of June (C) and end of July (C++).

I'm using the latest released version iceoryx2 = "0.3.0".

**Comment by elBoberido** [comment] 2024-06-22 13:28
@qpswwww we need a fully working example which triggers the hang. Without that we are not able to find the root cause. For example, the code you provided does not compile and if changes were made to make it compile, it would block in `request_channel_recver.recv()` in the `rust_part::launch_request_service_daemon();` call. Looking at the provided code, I cannot see anything that would make it hang with iceoryx as the root cause.

The C examples are currently just there to test CI setup and build system. The actual code will be added the next weeks.

**Comment by elBoberido** [comment] 2024-07-03 00:23
@qpswwww like mentioned in the previous comment, we need a working minimal example which triggers the bug you describe

**Comment by elfenpiff** [comment] 2024-07-20 19:02
@qpswwww I am closing the issue since we require a minimal working example that triggers the bug.

Please feel free to reopen the issue when you can provide an example.

**Closed by elfenpiff** 2024-07-20 19:02 UTC
Labels: bug, needs info
