### ISSUE TITLE
Cannot run in a non-UTF-8 environment on Windows 11

### ISSUE THREAD

**Issue by imxood** [eclipse-iceoryx/iceoryx2#145] opened 2024-03-07 07:41 UTC
## Required information

**Operating system:**
Windows 11 Pro 23H2 - 22631.3155 / Intel(R) Core(TM) i9-14900HX

**Rust version:**
rustc 1.77.0-nightly (f688dd684 2024-01-04)

**Cargo version:**
cargo 1.77.0-nightly (add15366e 2024-01-02)

**iceoryx2 version:**
`main` branch

**Observed result or behaviour:**

Iceoryx2 cannot run properly in a non-UTF8 environment on Windows
![image](https://github.com/eclipse-iceoryx/iceoryx2/assets/14890680/27905392-166b-4f4a-b9b2-eda6b33b39e3)

When UTF-8 is enabled, it can run successfully.
![image](https://github.com/eclipse-iceoryx/iceoryx2/assets/14890680/c0ae880e-4ad3-45cd-b581-9d8e00e660ab)
![image](https://github.com/eclipse-iceoryx/iceoryx2/assets/14890680/1f74ca23-d30e-4d3c-b485-3e355d310c75)

**Comment by elfenpiff** [comment] 2024-03-07 11:04
@imxood Thanks for the report. I fixed the issue and the PR is now merged.

Could you please confirm that the problem is now solved on the `main` branch? I cannot do it myself, since I do not have a non-utf-8 Windows environment at my disposal.

**Comment by imxood** [comment] 2024-03-07 11:12
@elfenpiff it's so cool, the problem is solved, thank you very much~

**Closed** 2024-03-07 11:12 UTC
Labels: bug
