### ISSUE TITLE
run event_based_communication on C++

### ISSUE THREAD

**Issue by owny990312** [eclipse-iceoryx/iceoryx2#566] opened 2024-12-24 02:39 UTC
when I first run ./example_cxx_event_based_communication_subscriber,
then run ./example_cxx_event_based_communication_publisher, the publisher is coredump like the following picture:

![image](https://github.com/user-attachments/assets/871b4cf7-fc19-4d82-8a3d-3859b879a644)

But when I first run  example_cxx_event_based_communication_publisher 
then run  ./example_cxx_event_based_communication_subscriber,it works.

But In my case, it must run subscriber first.

**Comment by elfenpiff** [comment] 2024-12-24 08:37
@owny990312 Thanks for the bug-report - I can confirm the bug! It is only present in the C++ version of the example. I suppose it is a bug in the example itself.

**Comment by elfenpiff** [comment] 2024-12-24 08:42
@owny990312 the problem was that the publisher and the subscriber had inconsistent history requirements. This is fixed with #567

**Comment by owny990312** [comment] 2024-12-24 08:49
> @owny990312 the problem was that the publisher and the subscriber had inconsistent history requirements. This is fixed with #567问题是出版商和订阅者的历史要求不一致。这通过 #567 解决了。

Thanks for your reply

**Comment by owny990312** [comment] 2024-12-24 08:51
> @owny990312 the problem was that the publisher and the subscriber had inconsistent history requirements. This is fixed with #567问题是出版商和订阅者的历史要求不一致。这通过 #567 解决了。

By the way ,what is the function of HISTORY_SIZE

**Closed** 2024-12-24 13:09 UTC
Labels: bug

**Comment by elfenpiff** [comment] 2024-12-24 13:11
`HISTORY_SIZE` determines how many previously delivered samples the publisher will send to the subscriber when the subscriber connects. In this case, the subscriber would receive up to the latest 20 samples from the publisher on connection.
